### ISSUE TITLE
Spacing between inputs on medium/large sized pages

### ISSUE THREAD

**Issue by bensullivan8** [bensullivan8/volunteer-form#1]
Hi there,
I'm having some trouble figuring out the proper way to create the gap between text inputs when they are at 50% widths on medium and large-sized browser windows. Would you be able to take a look at my code and see what I need to add? Thank you.

Ben Sullivan

@muxlowc

**Comment by muxlowc** [comment]
@bensullivan8 have you tried adding a "gutter-1-2" on your div surrounding your input/label? I think if you do this for all of them, then it should work. Example:

```
<div class="push unit xs-1 m-1-2 l-1-2 gutter-1-2">
  <label class="push-1-8" for="name">Full name</label>
  <input id="name" name="name" required>
  <em class="micro">Your full legal name, for insurance purposes, e.g. “Elizabeth Bradley”.</em>
</div>
```

**Comment by bensullivan8** [comment]
Thank you for your help. I really appreciate it.
